### PR TITLE
Fix client-go version in go.mod

### LINKED ISSUE #52: wrong client-go version in go.mod
Now:
k8s.io/client-go v1.19.0
Should be:
k8s.io/client-go v0.19.0

Error message:
go: github.com/kubernetes-csi/csi-lib-utils@v0.8.0 requires
	k8s.io/client-go@v1.19.0: reading k8s.io/client-go/go.mod at revision v1.19.0: unknown revision v1.19.0

### PR DESCRIPTION
**Pull request by avorima**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Without this a replace is needed in the go.mod of dependent repos.
Also cleanup up indirect imports as a fly-by.

**Which issue(s) this PR fixes**:

Fixes #52 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix k8s.io/client-go version in go.mod
```

### CODE REVIEW

**Comment by pohly** [comment]
That broke in https://github.com/kubernetes-csi/csi-lib-utils/pull/50.

@humblec  did you manually edit the v1.19.9 into go.mod? 

What's puzzles me is that Go never complained. There isn't even such a tag!

This fails, as expected:
```
$ go get k8s.io/client-go@v1.19.0
go get k8s.io/client-go@v1.19.0: k8s.io/client-go@v1.19.0: invalid version: unknown revision v1.19.0
```

But `go mod tidy` and `make` just work fine.

Ah, that's because of the `
replace k8s.io/client-go => k8s.io/client-go v0.19.0`

Those replace statements are redundant, but that's not something that `go-get-kubernetes.sh` can determine easily, in particular not in advance. It would be nice to check for consistency as part of `make test-vendor`, but I am not sure how to do that.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
@avorima please run "go mod vendor" and include those changes in the commit. We still do vendoring in this repo.

**Comment by avorima** [comment]
@pohly Sorry, I missed that. Thanks for taking a look at this on such short notice

**Comment by pohly** [comment]
I'm still puzzled that this typo had some effect (indirect dependency on groupcache and ginkgo in go.mod). Anyway:
/lgtm

**Comment by pohly** [comment]
> Those replace statements are redundant, but that's not something that go-get-kubernetes.sh can determine easily, in particular not in advance. It would be nice to check for consistency as part of make test-vendor, but I am not sure how to do that.

I extended go-get-kubernetes.sh to remove such redundant replace statements, only to be reminded that they are not redundant when actually using k8s.io/kubernetes:
```
go: k8s.io/kubernetes@v1.19.0 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

So I think we should leave everything as it is now and just need to be more careful during the next dependency update, in particular use the script instead of manually editing files. I checked it: "go-get-kubernetes.sh 1.19.0" does fix the "client-go" version.

**Comment by humblec** [comment]
@pohly iirc,  I manually edited the file, that could have caused it :(..

**Pull request merged**
