### PR TITLE
metrics: optional process_start_time

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

The `process_start_time` as registered by csi-lib-utils and thus
Kubernetes component base conflicts with the one from the Prometheus
Golang collector, leading to this error:

```
gathered metric family process_start_time_seconds has help "[ALPHA] Start time of the process since unix epoch in seconds." but should have "Start time of the process since unix epoch in seconds."
```

Allowing processes to control where they get the metric from solves
this conflict.

**Does this PR introduce a user-facing change?**:
```release-note
process_start_time should be unique in a process and therefore can now be disabled in the metrics manager registry if not needed or when it conflicts with other collectors
```

### CODE REVIEW

**Comment by Jiawei0227** [comment]
/lgtm

There is also another bug fix I opened in k8s for this: https://github.com/kubernetes/kubernetes/pull/96435
Actually I am surprised you can get the process_start_time_seconds in the csi-lib-utils to work. Did you have multiple CSIMetricsManager?

**Comment by pohly** [comment]
> Actually I am surprised you can get the process_start_time_seconds in the csi-lib-utils to work. Did you have multiple CSIMetricsManager?

I think I manually tested with multiple instances before the original PR merged, but that was a one-time thing. I've never actually verified that `process_start_time_seconds` works as intended.

I'm using Prometheus, and that seems to work fine also without it.

**Comment by Jiawei0227** [comment]
> I'm using Prometheus, and that seems to work fine also without it.

Yep, sounds good then. Prometheus will by default register a couple of process related metrics which is good. But all our csi sidecars are only using this registry which dont have this metric. This has been proven problematic because some other OSS library assume we have it and it can cause parsing problem. That's why I added it.

**Comment by pohly** [comment]
> Prometheus will by default register a couple of process related metrics which is good. But all our csi sidecars are only using this registry which dont have this metric. 

I'm wondering whether we should change the sidecars to enable the Prometheus Golang collector.  Does anyone know how useful those metrics are in practice? I don't.

**Comment by Jiawei0227** [comment]
> I'm wondering whether we should change the sidecars to enable the Prometheus Golang collector. Does anyone know how useful those metrics are in practice? I don't.

The thing is we are using our own wrapper around prometheus metrics which is a thing called KubeRegistry in component-base library. And that does not have the prometheus golang collector... here is the issue:
https://github.com/kubernetes/kubernetes/issues/95152

**Comment by pohly** [comment]
> The thing is we are using our own wrapper around prometheus metrics which is a thing called KubeRegistry in component-base library. And that does not have the prometheus golang collector...

That doesn't mean that a sidecar can't add those if it wants. But I understand that it then diverges from the rest of Kubernetes (no definition of metrics stability), so that may not be desirable.

For PMEM-CSI, I enabled it because we have our own definition of "stable features".

**Pull request merged**
