### PR TITLE
update to k/k 1.16

### PR DESCRIPTION
**Pull request by jichenjc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
solving https://github.com/kubernetes/cloud-provider-openstack/issues/702 as I have to include leaderelection file into cloud provider openstack and when running `dep ensure` I have following error, seems csi-lib-utils still rely on k/k1.14 while conflict to cloud provider openstack on 1.16

Solving failure: No versions of github.com/kubernetes-csi/csi-lib-utils met constraints:
        v0.6.1: Could not introduce github.com/kubernetes-csi/csi-lib-utils (from https://github.com/kubernetes-csi/csi-lib-utils)@v0.6.1, as it has a dependency on k8s.io/client-go with constraint kubernetes-1.14.0, which has no overlap with existing constraint kubernetes-1.16.0 from (root)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/assign @andrewsykim

Can you have a look at this? I don't know what the implications will be for other users of this lib if we bump the Kubernetes dependency to 1.16.

The underlying problem is that Kubernetes packages don't have semantic versioning. So even though csi-lib-utils seems to be compatible with any version >= 1.14 (or at least no code changes were necessary to compile with 1.16), we can't specify that in the `Gopkg.toml` file.

I don't know for sure how Go modules would handle this. I suspect it would allow us to select 1.14 for reproducible builds of `csi-lib-utils`, but as this isn't a minimal viable version with semantic versioning, users might accidentally pick something older.

**Comment by pohly** [comment]
Perhaps we can approximate the `go mod` behavior by removing the constraints from `Gopkg.toml`?

**Comment by jichenjc** [comment]
can we create a new tag e.g 0.6.2 if we bump to k/k 1.16 so older still can rely on 0.6.1? and for newer can rely on 0.6.2

the go mod might be another way to try as well

**Comment by andrewsykim** [comment]
@jichenjc would an override in your Gopkg.toml file work for the kubernetes dependencies work?

**Comment by pohly** [comment]
@jichenjc: can you try whether the switch to go modules (https://github.com/kubernetes-csi/csi-lib-utils/pull/33) works for you?

**Comment by jichenjc** [comment]
ok, will try it later on (holiday approaching), thanks~

**Comment by pohly** [comment]
PR #33 was merged, please let us know whether this is still needed.

**Comment by jichenjc** [comment]
let me close this and let me try with go module first, if needed, might open another one. thanks~

**Pull request closed without merging**
