### PR TITLE
fixing scripts that used to point to https://github.com/google/protob…

### PR DESCRIPTION
**Pull request by GM1957**
…uf/releases to the new location https://github.com/protocolbuffers/protobuf/releases

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NO

```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
The change itself looks uncontroversial. Is there a particular reason for changing this, though?

**Comment by GM1957** [comment]
> The change itself looks uncontroversial. Is there a particular reason for changing this, though?

hey @pohly please check this https://github.com/google/protobuf.dart/issues/532#issuecomment-888515218

**Pull request merged**
