### PR TITLE
Add GetGroupControllerCapabilities common function

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

`external-volumesnapshot` want to use it to check group controller caps

**Does this PR introduce a user-facing change?**:

```release-note
Add GetGroupControllerCapabilities common function
```

### CODE REVIEW

**Comment by carlory** [comment]
/hold

It's blocked by  #132

**Comment by xing-yang** [comment]
Can you add a unit test?

**Comment by carlory** [comment]
/hold cancel

> Can you add a unit test?

@xing-yang added.

**Pull request merged**
