### PR TITLE
WIP: new update k8s 1.30 (testing CI)

### PR DESCRIPTION
**Pull request by pohly**
Please ignore, just testing the CI.

### CODE REVIEW

**Comment by pohly** [comment]
/retest

My logcheck fork was bumped to 1.22.

**Comment by pohly** [comment]
/test pull-kubernetes-csi-csi-lib-utils

With "go 1.20" in logtools.

**Comment by jsafrane** [comment]
/close 
We updated logcheck to 0.8.2 that works well with go 1.22

**Pull request closed without merging**
